routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/mensalidades', function (){
    $users = \App\Models\Financeiro::where('mensalidade','1')->groupBy('associado_id')
                                    ->select('associado_id','mensalidade', DB::raw('count(*) as total'))
                                    ->orderBy('total','desc')
                                    ->get();
    return view('mensalidades',compact('users'));
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/associados','\App\Http\Controllers\AssociadoController');
Route::get('/associados/{id}/financeiro',[\App\Http\Controllers\AssociadoController::class,'financeiro'])->name('associados.financeiros.index');
Route::any('/associados/search',[\App\Http\Controllers\AssociadoController::class,'search'])->name('associados.search');
Route::post('/associados/{id}/financeiro',[\App\Http\Controllers\AssociadoController::class,'financeiroStore'])->name('associados.financeiros.store');
Route::resource('/financeiros','\App\Http\Controllers\FinanceiroController');

app/Models/Financeiro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Financeiro extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $dates = ['data','deleted_at'];

    public function associados()
    {
        return $this->belongsTo(Associado::class,'associado_id');
    }
}

app/Http/Controllers/FinanceiroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Associado;
use App\Models\Financeiro;
use Illuminate\Http\Request;
use function GuzzleHttp\Promise\all;

class FinanceiroController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $financeiros = Financeiro::orderBy('id','desc')->paginate(15);
        return view('financeiros.index', compact('financeiros'));
    }

    public function create()
    {
        $associados = Associado::select('id','nome')->get();
        return view('financeiros.create',compact('associados'));
    }

    public function store(Request $request)
    {
        $fin = new Financeiro();
        $fin->valor = str_replace(array(".", ","), array("", "."), $request->valor);
        if($request->tipo == 'e'){
            $fin->associado_id = $request->associado_id;
            $fin->mensalidade = $request->mensalidade;
            $fin->description = $request->description;
        } else if ($request->tipo == 's'){
            $fin->description = $request->description1;
        }
        $fin->tipo = $request->tipo;
        $fin->data = $request->data;
        $fin->save();

        return redirect()->route('financeiros.index')->with('success','Inserido com Sucesso!');
    }

    public function edit(Financeiro $financeiro)
    {
        $associados = Associado::select('id','nome')->get();
        return view('financeiros.edit',compact('financeiro','associados'));
    }

    public function update(Request $request, Financeiro $financeiro)
    {

        $financeiro->valor = str_replace(array(".", ","), array("", "."), $request->valor);
        if($request->tipo == 'e'){
            $financeiro->associado_id = $request->associado_id;
            $financeiro->mensalidade = $request->mensalidade;
            $financeiro->description = $request->description;
        } else if ($request->tipo == 's'){
            $financeiro->description = $request->description1;
        }
        $financeiro->tipo = $request->tipo;
        $financeiro->data = $request->data;
        $financeiro->save();

        return redirect()->route('financeiros.edit',$financeiro->id)->with('success','Atualizado com Sucesso!');
    }

    public function destroy(Financeiro $financeiro)
    {
        $financeiro->delete();
        return redirect()->route('financeiros.index')->with('success','Deletado com Sucesso!');
    }
}

resources/views/financeiros/create.blade.php
@extends('layouts.app')

@section('content')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
    <div class="row">
        <div class="col-lg-12">
            <h3>Adicionar</h3>
        </div>
        <div class="col-md-8">
            <div class="card rounded-0">
                <div class="card-body">
                    <form action="{{route('financeiros.store')}}" method="post" class="row g-3" novalidate>
                        @csrf
                        <div class="col-md-3 mb-3 me-3">
                            <label for="valor">Valor</label>
                            <input type="text" name="valor" class="form-control rounded-0 valor" required>
                        </div>
                        <div class="col-md-5 mb-3">
                            <label for="nome" class="d-block mb-2">Tipo</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="inlineRadio1" value="e" required>
                                <label class="form-check-label" for="inlineRadio1">Entrada</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="inlineRadio2" value="s" required>
                                <label class="form-check-label" for="inlineRadio2">Saida</label>
                            </div>
                        </div>
                        <div id="e" class="d-none">
                            <div class="col-md-4 mb-3">
                                <label for="nome" class="d-block mb-2">Mensalidade</label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade1" value="1" required>
                                    <label class="form-check-label" for="mensalidade1">Sim</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade2" value="0" required>
                                    <label class="form-check-label" for="mensalidade2">Não</label>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="associado">Associado</label>
                                <select name="associado_id" id="associado_id" class="form-control js-example-basic-single">
                                    <option value="">Selecione</option>
                                @foreach($associados as $a)
                                    <option value="{{$a->id}}">{{$a->nome}}</option>
                                @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="description">Descrição</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                        <div id="s" class="d-none">
                            <div class="mb-3">
                                <label for="description1">Descrição</label>
                                <textarea name="description1" id="description1" class="form-control" cols="30" rows="10"></textarea>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="data">Data</label>
                            <input type="date" name="data" class="form-control rounded-0" required>
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-primary btn-sm rounded-0 float-end">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="/js/jquery.mask.js"></script>
    <script>
        $(document).ready(function(){
            $('.valor').mask('999.999,99',{reverse: true});
        });
        window.onload = function(){
            onclick = function(){
                var tipo = document.querySelector('input[name = tipo]:checked').value;
                if(tipo == 'e'){
                    $('#e').removeClass('d-none');
                    $('#s').addClass('d-none');
                }else if(tipo == 's'){
                    $('#s').removeClass('d-none');
                    $('#e').addClass('d-none');
                }
            }
        }
        $(document).ready(function() {
            $('.js-example-basic-single').select2({
                theme: 'bootstrap4',
            });

        });
    </script>
@endpush

resources/views/financeiros/edit.blade.php
@extends('layouts.app')

@section('content')
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
    <div class="row">
        <div class="col-lg-12">
            <h3>Adicionar</h3>
        </div>
        <div class="col-md-8">
            <div class="card rounded-0">
                <div class="card-body">
                    <form action="{{route('financeiros.update',$financeiro->id)}}" method="post" class="row g-3">
                        @csrf
                        @method('PUT')
                        <div class="col-md-2 mb-3 me-3">
                            <label for="valor">Valor</label>
                            <input type="text" name="valor" class="form-control rounded-0 valor" value="{{number_format($financeiro->valor,2,',','.')}}" required>
                        </div>
                        <div class="col-md-5 mb-3">
                            <label for="nome" class="d-block mb-2">Tipo</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="inlineRadio1" value="e" {{$financeiro->tipo == 'e'?'checked':''}} required>
                                <label class="form-check-label" for="inlineRadio1">Entrada</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="tipo" id="inlineRadio2" value="s" {{$financeiro->tipo == 's'?'checked':''}} required>
                                <label class="form-check-label" for="inlineRadio2">Saida</label>
                            </div>
                        </div>
                        <div id="e" class="d-none">
                            <div class="col-md-4 mb-3">
                                <label for="nome" class="d-block mb-2">Mensalidade</label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade1" value="1" {{$financeiro->mensalidade == '1'?'checked':''}} required>
                                    <label class="form-check-label" for="mensalidade1">Sim</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade2" value="0" {{$financeiro->mensalidade == '0'?'checked':''}} required>
                                    <label class="form-check-label" for="mensalidade2">Não</label>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="associado">Associado</label>
                                <select name="associado_id" id="associado_id" class="form-control js-example-basic-single">
                                    <option value="">Selecione</option>
                                    @foreach($associados as $a)
                                        <option value="{{$a->id}}" @if($financeiro->associado_id == $a->id) selected @endif>{{$a->nome}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="description">Descrição</label>
                                <textarea name="description" id="description" class="form-control" cols="30" rows="10">{{$financeiro->description}}</textarea>
                            </div>
                        </div>
                        <div id="s" class="d-none">
                            <div class="mb-3">
                                <label for="description1">Descrição</label>
                                <textarea name="description1" id="description1" class="form-control" cols="30" rows="10">{{$financeiro->description}}</textarea>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="data">Data</label>
                            <input type="date" name="data" class="form-control rounded-0" value="{{$financeiro->data->format('Y-m-d')}}" required>
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-primary btn-sm rounded-0 float-end">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="/js/jquery.mask.js"></script>
    <script>
        $(document).ready(function(){
            $('.valor').mask('999.999,99',{reverse: true});
        });
        window.onload = function(){
            onclick = function(){
                var tipo = document.querySelector('input[name = tipo]:checked').value;
                if(tipo == 'e'){
                    $('#e').removeClass('d-none');
                    $('#s').addClass('d-none');
                }else if(tipo == 's'){
                    $('#s').removeClass('d-none');
                    $('#e').addClass('d-none');
                }
            }
        }
        $(document).ready(function() {
            $('.js-example-basic-single').select2({
                theme: 'bootstrap4',
            });
            @if($financeiro->tipo == 'e')
                $('#inlineRadio1').attr('checked', true);
                $('#e').removeClass('d-none');
                $('#s').addClass('d-none');
            @else
                $('#inlineRadio2').attr('checked', true);
                $('#s').removeClass('d-none');
                $('#e').addClass('d-none');
            @endif
        });
    </script>
@endpush

resources/views/financeiros/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h3 class="fw-lighter">
                Finanças
                <a class="btn btn-sm btn-primary float-end" href="{{route('financeiros.create')}}">+add</a>
            </h3>

        </div>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Valor</th>
                            <th>Data</th>
                        </tr>
                    </thead>
                    <tbody>
                    @forelse($financeiros as $f)
                        <tr class="{{$f->tipo == 'e'?'text-success':'text-danger'}}">
                            <td>
                            @if($f->tipo == 'e')
                                {{$f->mensalidade == '1'?'Mensalidade':$f->description}}: {{$f->associados->nome}}
                            @else
                                {{$f->description}}
                            @endif
                            </td>
                            <td><b>{{ number_format($f->valor,2,',','.')}}</b></td>
                            <td>{{$f->data->format('d/m/Y')}}</td>
                            <td><a class="btn btn-info btn-sm rounded-0" href="{{route('financeiros.edit',$f->id)}}"><i class="fa fa-edit"></i></a></td>
                            <td>
                                <form action="{{route('financeiros.destroy',$f->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm rounded-0" href=""><i class="fa fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3">Sem Movimentações</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>
            {{$financeiros->links()}}
        </div>
    </div>
@endsection