routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/mensalidades', function (){
    $users = \App\Models\Financeiro::where('mensalidade','1')->groupBy('associado_id')
                                    ->select('associado_id','mensalidade', DB::raw('count(*) as total'))
                                    ->orderBy('total','desc')
                                    ->get();
    return view('mensalidades',compact('users'));
});

Auth::routes([
    'register' => false, // Registration Routes...
    'reset' => false, // Password Reset Routes...
    'verify' => false, // Email Verification Routes...
]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('/associados','\App\Http\Controllers\AssociadoController');
Route::get('/associados/{id}/financeiro',[\App\Http\Controllers\AssociadoController::class,'financeiro'])->name('associados.financeiros.index');
Route::any('/associados/search',[\App\Http\Controllers\AssociadoController::class,'search'])->name('associados.search');
Route::post('/associados/{id}/financeiro',[\App\Http\Controllers\AssociadoController::class,'financeiroStore'])->name('associados.financeiros.store');
Route::resource('/financeiros','\App\Http\Controllers\FinanceiroController');

app/Models/Associado.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Associado extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $dates = ['nascimento','deleted_at'];
}

app/Http/Controllers/AssociadoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Associado;
use App\Models\Financeiro;
use Illuminate\Http\Request;

class AssociadoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $associados = Associado::orderBy('id','desc')->paginate(10);
        return view('associados.index',compact('associados'));
    }

    public function create()
    {
        return view('associados.create');
    }

    public function store(Request $request)
    {
        $this->validate(request(),[
            'nome' => ['required', 'string', 'max:255'],
        ]);

        $associado = new Associado();
        $associado->nome = $request->nome;
        $associado->apelido = $request->apelido;
        $associado->contato = $request->contato;
        $associado->nascimento = $request->nascimento;
        $associado->save();

        return redirect()->route('associados.index')->with('success','Associado Inserido com Sucesso');
    }

    public function show(Associado $associado)
    {
        $financeiros = Financeiro::where('associado_id',$associado->id)->orderBy('data','asc')->get();
        return view('associados.show',compact('associado','financeiros'));
    }

    public function financeiro($id)
    {
        $associado = Associado::find($id);
        $financeiros = Financeiro::where('associado_id',$id)->orderBy('data','asc')->get();
        return view('associados.financeiro',compact('associado','financeiros'));
    }

    public function financeiroStore(Request $request, $id)
    {
        $fin = new Financeiro();
        $fin->valor = str_replace(array(".", ","), array("", "."), $request->valor);
        if($request->tipo == 'e'){
            $fin->associado_id = $request->associado_id;
            $fin->mensalidade = $request->mensalidade;
            $fin->description = $request->description;
        } else if ($request->tipo == 's'){
            $fin->description = $request->description1;
        }
        $fin->tipo = $request->tipo;
        $fin->data = $request->data;
        $fin->save();

        return redirect()->route('associados.financeiros.index',$id)->with('success','Inserido com Sucesso!');
    }

    public function edit(Associado $associado)
    {
        return view('associados.edit',compact('associado'));
    }

    public function update(Request $request, Associado $associado)
    {
        $this->validate(request(),[
            'nome' => ['required', 'string', 'max:255'],
        ]);

        $associado->nome = $request->nome;
        $associado->apelido = $request->apelido;
        $associado->contato = $request->contato;
        $associado->nascimento = $request->nascimento;
        $associado->save();

        return redirect()->route('associados.edit',$associado)->with('success','Associado Atualizado com Sucesso');
    }

    public function search()
    {
        $q = \Request::get('q');
        $associados = Associado::where('nome','like','%'.$q.'%')
                              ->orWhere('apelido','like','%'.$q.'%')
                              ->get();
        if($associados->count() > 0){
            return view('associados.search',compact('associados'));
        }else{
            return back()->with('warning','Associado Não Encontrado');
        }
    }

    public function destroy(Associado $associado)
    {
        //
    }
}

resources/views/associados/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h3>Adicionar Associado</h3>
        </div>
        <div class="col-md-8">
            <div class="card rounded-0">
                <div class="card-body">
                    <form action="{{route('associados.store')}}" method="post">
                        @csrf
                        <div class="mb-3">
                            <label for="nome">Nome (<span class="small text-muted">ou apelido</span>)</label>
                            <input type="text" name="nome" class="form-control rounded-0" required>
                        </div>
                        <div class="mb-3">
                            <label for="apelido">Apelido (<span class="small text-muted">opcional</span>)</label>
                            <input type="text" name="apelido" class="form-control rounded-0">
                        </div>
                        <div class="mb-3">
                            <label for="contato">Contato (<span class="small text-muted">opcional</span>)</label>
                            <input type="tel" name="contato" maxlength="11" class="form-control rounded-0">
                        </div>
                        <div class="mb-3">
                            <label for="nascimento">Nascimento (<span class="small text-muted">opcional, só números</span>)</label>
                            <input type="date" name="nascimento" class="form-control rounded-0">
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-primary btn-sm rounded-0 float-end">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/associados/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h3>Editar Associado: {{$associado->nome}}</h3>
        </div>
        <div class="col-md-8">
            <div class="card rounded-0">
                <div class="card-body">
                    <form action="{{route('associados.update',$associado->id)}}" method="post">
                        @csrf
                        @method('PUT')
{{--                            <div class="mb-3">--}}
{{--                                <label for="time">Time (<span class="small text-muted">ou apelido</span>)</label>--}}
{{--                                <select name="time" id="time" class="form-control">--}}
{{--                                    <option value="">Selecione</option>--}}
{{--                                    <option value=""></option>--}}
{{--                                </select>--}}
{{--                            </div>--}}
                        <div class="mb-3">
                            <label for="nome">Nome (<span class="small text-muted">ou apelido</span>)</label>
                            <input type="text" name="nome" class="form-control rounded-0" value="{{$associado->nome}}" required>
                        </div>
                        <div class="mb-3">
                            <label for="apelido">Apelido (<span class="small text-muted">opcional</span>)</label>
                            <input type="text" name="apelido" class="form-control rounded-0" value="{{$associado->apelido}}">
                        </div>
                        <div class="mb-3">
                            <label for="contato">Contato (<span class="small text-muted">opcional, só números</span>)</label>
                            <input type="tel" name="contato" maxlength="11" class="form-control rounded-0" value="{{$associado->contato}}">
                        </div>
                        <div class="mb-3">
                            <label for="nascimento">Nascimento (<span class="small text-muted">opcional</span>)</label>
                            <input type="date" name="nascimento" class="form-control rounded-0" value="@isset($associado->nascimento){{$associado->nascimento->format('Y-m-d')}}@endisset">
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-primary btn-sm rounded-0 float-end">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/associados/financeiro.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h3>Mensalidades de {{$associado->nome}}</h3>
        </div>
        <div class="col-lg-8">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('associados.financeiros.store',$associado->id)}}" method="post" class="row g-3">
                        @csrf
                        <input type="hidden" name="tipo" value="e">
                        <input type="hidden" name="associado_id" value="{{$associado->id}}">
                        <div class="col-md-4 mb-1">
                            <label for="valor">Valor</label>
                            <input type="text" name="valor" class="form-control rounded-0 valor" required autocomplete="off"/>
                        </div>
                        <div class="col-md-4 mb-1">
                            <label for="data">Data</label>
                            <select name="data" id="data" class="form-select" required>
                                <option value="">Selecione</option>
                                <option value="2022-01-22" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-01-22','mensalidade'=>'1'])->first()) disabled @endif>22 Jan</option>
                                <option value="2022-02-19" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-02-19','mensalidade'=>'1'])->first()) disabled @endif>19 Fev</option>
                                <option value="2022-03-19" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-03-19','mensalidade'=>'1'])->first()) disabled @endif>19 Mar</option>
                                <option value="2022-04-23" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-04-23','mensalidade'=>'1'])->first()) disabled @endif>23 Abr</option>
                                <option value="2022-05-21" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-05-21','mensalidade'=>'1'])->first()) disabled @endif>21 Mai</option>
                                <option value="2022-06-18" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-06-18','mensalidade'=>'1'])->first()) disabled @endif>18 Jun</option>
                                <option value="2022-07-23" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-07-23','mensalidade'=>'1'])->first()) disabled @endif>23 Jul</option>
                                <option value="2022-08-20" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-08-20','mensalidade'=>'1'])->first()) disabled @endif>20 Ago</option>
                                <option value="2022-09-17" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-09-17','mensalidade'=>'1'])->first()) disabled @endif>17 Set</option>
                                <option value="2022-10-22" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-10-22','mensalidade'=>'1'])->first()) disabled @endif>22 Out</option>
                                <option value="2022-11-19" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-11-19','mensalidade'=>'1'])->first()) disabled @endif>19 Nov</option>
                                <option value="2022-12-24" @if(\App\Models\Financeiro::select('data')->where(['associado_id'=>$associado->id,'data'=>'2022-12-24','mensalidade'=>'1'])->first()) disabled @endif>24 Dez</option>
                            </select>
                        </div>
                        <div class="col-md-4 mb-1">
                            <label for="nome" class="d-block mb-2">Mensalidade</label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade1" value="1" required>
                                <label class="form-check-label" for="mensalidade1">Sim</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="mensalidade" id="mensalidade2" value="0" required>
                                <label class="form-check-label" for="mensalidade2">Não</label>
                            </div>
                        </div>
                        <div class="mb-1">
                            <label for="description">Descrição</label>
                            <textarea name="description" id="description" class="form-control" cols="30" rows="10"></textarea>
                        </div>
                        <div id="s" class="d-none">
                            <div class="mb-3">
                                <label for="description1">Descrição</label>
                                <textarea name="description1" id="description1" class="form-control" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                        <div class="">
                            <button type="submit" class="btn btn-primary btn-sm rounded-0 float-end">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="card">
                <div class="card-body">
                    <h3>Pagamentos</h3>
                    @foreach($financeiros as $f)
                        <li>{{$f->data->format('d M Y')}} (@if($f->mensalidade == '1') mensalidade @else outros @endif )</li>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script src="/js/jquery.mask.js"></script>
    <script>
        $(document).ready(function(){
            $('.valor').mask('999.999,99',{reverse: true});
        });
        window.onload = function(){
            onclick = function(){
                var tipo = document.querySelector('input[name = tipo]:checked').value;
                if(tipo == 'e'){
                    $('#e').removeClass('d-none');
                    $('#s').addClass('d-none');
                }else if(tipo == 's'){
                    $('#s').removeClass('d-none');
                    $('#e').addClass('d-none');
                }
            }
        }
    </script>
@endpush

resources/views/associados/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg">
            <h3 class="fw-light">
                Associados
                <a class="btn btn-sm btn-primary float-end" href="{{route('associados.create')}}">+add Associado</a>
            </h3>
            <form action="{{route('associados.search')}}" method="post">
                @csrf
                <div class="input-group mb-3">
                    <input type="text" name="q" class="form-control" placeholder="Nome ou Apelido" aria-label="Recipient's username" aria-describedby="button-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#ID</th>
                            <th>Nome/Apelido</th>
                            <th>Contato</th>
                            <th>Nascimento</th>
                            <th colspan="2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($associados as $a)
                            <tr>
                                <td>{{$a->id}}</td>
                                <td>{{$a->nome}}</td>
                                <td>{{$a->contato}}</td>
                                <td>{{ $a->nascimento ?$a->nascimento->format('d/m/Y'):''}}</td>
                                <td><a class="btn btn-info btn-sm rounded-0" href="{{route('associados.edit',$a->id)}}"><i class="fa fa-edit"></i></a></td>
                                <td><a class="btn btn-primary btn-sm rounded-0" href="{{route('associados.show',$a->id)}}"><i class="fa fa-eye"></i></a></td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">Sem Associados</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
            {{$associados->links()}}
        </div>
    </div>
@endsection

resources/views/associados/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg">
            <h3 class="fw-light">
                Associados
                <a class="btn btn-sm btn-primary float-end" href="{{route('associados.create')}}">+add Associado</a>
            </h3>
            <form action="{{route('associados.search')}}" method="post">
                @csrf
                <div class="input-group mb-3">
                    <input type="text" name="q" class="form-control" placeholder="Nome ou Apelido" aria-label="Recipient's username" aria-describedby="button-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="submit" id="button-addon2"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-12">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#ID</th>
                        <th>Nome/Apelido</th>
                        <th>Contato</th>
                        <th>Nascimento</th>
                        <th colspan="2"></th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($associados as $a)
                        <tr>
                            <td>{{$a->id}}</td>
                            <td>{{$a->nome}}</td>
                            <td>{{$a->contato}}</td>
                            <td>{{ $a->nascimento ?$a->nascimento->format('d/m/Y'):''}}</td>
                            <td><a class="btn btn-info btn-sm rounded-0" href="{{route('associados.edit',$a->id)}}"><i class="fa fa-edit"></i></a></td>
                            <td><a class="btn btn-primary btn-sm rounded-0" href="{{route('associados.show',$a->id)}}"><i class="fa fa-eye"></i></a></td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4">Sem Associados</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>
            </div>

        </div>
    </div>
@endsection

resources/views/associados/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-10">
            <div class="card rounded-0 text-light bg-info">
                <div class="card-body">
                    <h3 class="card-title">Associado: {{$associado->nome}}</h3>
                    <p class="card-text mb-0"><b>Nome:</b> {{$associado->nome}}</p>
                    <p class="card-text mb-0"><b>Apelido:</b> {{$associado->apelido}}</p>
                    <p class="card-text mb-0"><b>Contato:</b> {{$associado->contato}}</p>
                    <p class="card-text mb-3"><b>Nascimemnto:</b> @isset($associado->nascimento){{$associado->nascimento->format('Y-m-d')}}@endisset</p>
                    {{--                            <div class="mb-3">--}}
                    {{--                                <label for="time">Time (<span class="small text-muted">ou apelido</span>)</label>--}}
                    {{--                                <select name="time" id="time" class="form-control">--}}
                    {{--                                    <option value="">Selecione</option>--}}
                    {{--                                    <option value=""></option>--}}
                    {{--                                </select>--}}
                    {{--                            </div>--}}
                </div>
            </div>
        </div>
        <div class="col-lg-10 pt-3">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">
                        Pagamentos
                        <a href="{{route('associados.financeiros.index',$associado->id)}}" class="btn btn-primary btn-sm float-end">+add <i class="fa fa-dollar"></i></a>
                    </h3>

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Descrição</th>
                                <th>Valor</th>
                                <th>Data</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($financeiros as $f)
                                <tr class="{{$f->tipo == 'e'?'text-success':'text-danger'}}">
                                    <td>
                                        @if($f->tipo == 'e')
                                            {{$f->mensalidade == '1'?'Mensalidade':$f->description}}: {{$f->associados->nome}}
                                        @else
                                            {{$f->description}}
                                        @endif
                                    </td>
                                    <td><b>{{ number_format($f->valor,2,',','.')}}</b></td>
                                    <td>{{$f->data->format('d/m/Y')}}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="3">Sem Movimentações</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection